Controllers/BanksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Commercial;

namespace Commercial.Controllers
{
    public class BanksController : Controller
    {
        private dbCommercialEntities db = new dbCommercialEntities();

        // GET: Banks
        public ActionResult Index()
        {
            var bankList = db.tblBanks.ToList();
            return View(bankList);
        }

        // GET: Banks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblBank tblBank = db.tblBanks.Find(id);
            if (tblBank == null)
            {
                return HttpNotFound();
            }
            return View(tblBank);
        }

        // GET: Banks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Banks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,BankName")] tblBank tblBank)
        {
            if (ModelState.IsValid)
            {
                db.tblBanks.Add(tblBank);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblBank);
        }

        // GET: Banks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblBank tblBank = db.tblBanks.Find(id);
            if (tblBank == null)
            {
                return HttpNotFound();
            }
            return View(tblBank);
        }

        // POST: Banks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,BankName")] tblBank tblBank)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblBank).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblBank);
        }

        // GET: Banks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblBank tblBank = db.tblBanks.Find(id);
            db.tblBanks.Remove(tblBank);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // POST: Banks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblBank tblBank = db.tblBanks.Find(id);
            db.tblBanks.Remove(tblBank);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/MasterController.cs
using AutoMapper;
using Commercial.Helpers;
using Commercial.Models;
using Microsoft.Reporting.WebForms;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace Commercial.Controllers
{
    public class MasterController : Controller
    {
        // GET: Master
        private dbCommercialEntities db = new dbCommercialEntities();
        private readonly IMapper _mapper;
        public MasterController()
        {
            _mapper = AutoMapperProfiles.Mapper;
        }
        public ActionResult Index()
        {
            var masterList = db.tblMasters
                .Include("tblSupplier")
                .Include("tblBank").ToList();
            var viewList = new List<MasterViewModel>();
            viewList = _mapper.Map<List<MasterViewModel>>(masterList);
            return View(viewList);
        }
        public ActionResult Create()
        {
            MasterViewModel model = new MasterViewModel();
            model.BankList = db.tblBanks.ToList();
            model.SupplierList = db.tblSuppliers.ToList();
            model.DetailModel.ProductList = db.tblProducts.ToList();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MasterViewModel modelToSave)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    tblMaster entity = new tblMaster();
                    entity = _mapper.Map<tblMaster>(modelToSave);
                    db.tblMasters.Add(entity);
                    db.SaveChanges();

                    foreach (var item in modelToSave.DetailList)
                    {
                        tblDetail detailEntity = new tblDetail();
                        detailEntity = _mapper.Map<tblDetail>(item);
                        detailEntity.MasterId = entity.Id;
                        db.tblDetails.Add(detailEntity);
                    }
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.InnerException.ToString();
            }
            modelToSave.BankList = db.tblBanks.ToList();
            modelToSave.SupplierList = db.tblSuppliers.ToList();
            modelToSave.DetailModel.ProductList = db.tblProducts.ToList();
            return View(modelToSave);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblMaster tblmaster = db.tblMasters.Find(id);
            if (tblmaster == null)
            {
                return HttpNotFound();
            }
            MasterViewModel model = new MasterViewModel();
            model = _mapper.Map<MasterViewModel>(tblmaster);
            model.BankList = db.tblBanks.ToList();
            model.SupplierList = db.tblSuppliers.ToList();
            model.DetailModel.ProductList = db.tblProducts.ToList();

            List<tblDetail> detailList = db.tblDetails.Include("tblProduct").Where(x => x.MasterId == id).ToList();
            model.DetailList = _mapper.Map<List<DetailViewModel>>(detailList);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MasterViewModel model)
        {
            if (ModelState.IsValid)
            {
                tblMaster tblmaster = _mapper.Map<tblMaster>(model);
                db.Entry(tblmaster).State = EntityState.Modified;
                db.SaveChanges();

                if(model.DetailList.Count > 0)
                {
                    db.tblDetails.RemoveRange(db.tblDetails.Where(x => x.MasterId == tblmaster.Id).ToList());
                    foreach (var item in model.DetailList)
                    {
                        tblDetail detailToSave = _mapper.Map<tblDetail>(item);
                        db.tblDetails.Add(detailToSave);
                    }
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            try
            {
                tblMaster tblBank = db.tblMasters.Find(id);
                if(tblBank != null)
                {
                    List<tblDetail> details = db.tblDetails.Where(x => x.MasterId == id).ToList();
                    foreach (var item in details)
                    {
                        db.tblDetails.Remove(item);
                    }
                }
                db.tblMasters.Remove(tblBank);
                db.SaveChanges();
            }
            catch (Exception ex)
            {

            }
            
            return RedirectToAction("Index");
        }

        public ActionResult ViewReport(int id)
        {
            ReportViewer reportViewer = new ReportViewer();
            reportViewer.ProcessingMode = ProcessingMode.Local;
            reportViewer.SizeToReportContent = true;
            reportViewer.Width = Unit.Percentage(100);
            reportViewer.Height = Unit.Percentage(100);
            try
            {
                List<vw_MasterDetail> dataList = db.vw_MasterDetail.Where(x => x.Id == id).ToList();
                reportViewer.LocalReport.ReportPath = Request.MapPath(Request.ApplicationPath) + @"Reports\RptMasterDetail.rdlc";
                reportViewer.LocalReport.DataSources.Add(new ReportDataSource("dsMasterDetail", dataList));
                ViewBag.ReportViewer = reportViewer;
            }
            catch (Exception ex)
            {

                throw;
            }


            return View();
        }

        public PartialViewResult AddProductDetail(DetailViewModel model)
        {
            var master = new MasterViewModel();
            string prodName = db.tblProducts.FirstOrDefault(x => x.Id == model.ProductId).Name;
            model.ProductName = prodName;
            master.DetailList.Add(model);

            return PartialView("_Detail", master);
        }

        [HttpPost]
        public JsonResult GetProductInfo(int productId)
        {
            string msg = string.Empty;
            try
            {
                var obj = db.tblProducts.FirstOrDefault(x => x.Id == productId);
                if (obj != null)
                {
                    return Json(new
                    {
                        ProdName = obj.Name,
                        Description = obj.Description
                    });
                }
                else
                {
                    return Json(new { Result = false });
                }
            }
            catch (Exception ex)
            {
                return Json(new { Result = false });
            }
        }
    }
}

Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Commercial;

namespace Commercial.Controllers
{
    public class ProductsController : Controller
    {
        private dbCommercialEntities db = new dbCommercialEntities();

        // GET: Products
        public ActionResult Index()
        {
            return View(db.tblProducts.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblProduct tblProduct = db.tblProducts.Find(id);
            if (tblProduct == null)
            {
                return HttpNotFound();
            }
            return View(tblProduct);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Description")] tblProduct tblProduct)
        {
            if (ModelState.IsValid)
            {
                db.tblProducts.Add(tblProduct);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblProduct);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblProduct tblProduct = db.tblProducts.Find(id);
            if (tblProduct == null)
            {
                return HttpNotFound();
            }
            return View(tblProduct);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description")] tblProduct tblProduct)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblProduct).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblProduct);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblProduct tblProduct = db.tblProducts.Find(id);
            if (tblProduct == null)
            {
                return HttpNotFound();
            }
            db.tblProducts.Remove(tblProduct);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblProduct tblProduct = db.tblProducts.Find(id);
            db.tblProducts.Remove(tblProduct);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Commercial</title>
    <link href="~/Content/custom.css" rel="stylesheet" />
    <link href="~/Content/animate.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-chosen.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Monoton" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/fontawesome.css" rel="stylesheet" />
    <link href="~/Content/DataTables/css/dataTables.bootstrap.css" rel="stylesheet" />
    <link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-datepicker.min.css" rel="stylesheet" />
</head>
<body>
    <nav style="background-color: #152F4F;" class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand myclass  animated bounceInLeft" href="#" style="font-family: Monoton;">
            Commercial 
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="menual collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">

            @if (Session["UserName"] == null)
            {
                <div class="navbar-nav">
                    <a class="nav-item nav-link @ViewBag.Login" href="@Url.Action("Login", "Account")"><button class="btn btn-primary" style="width: 110px; height: 45px; background-color: #152F4F;"><i class="fas fa-sign-in-alt icn"></i> Login</button></a>
                    @*<a class="nav-item nav-link @ViewBag.Register" href="@Url.Action("Register", "Authentication")"><button class="btn btn-primary" style="width: 110px; height: 45px; background-color: #152F4F;"><i class="fas fa-user-plus"></i> Register</button></a>*@

                </div>
            }
            @if (Session["UserName"] != null)
            {
                <div class="navbar-nav">
                    <a class="nav-item nav-link @ViewBag.HomePage " href="@Url.Action("Index", "Home")"><button class="btn btn-primary" style="width: 120px; height: 45px; background-color: #152F4F;"><i class="fas fa-home"></i> Home </button></a>
                    <a class="nav-item nav-link @ViewBag.EmployeeAttendence " href="@Url.Action("Index", "Banks")"><button class="btn btn-primary" style="width: 120px; height: 45px; background-color: #152F4F;"> Banks </button></a>
                    <a class="nav-item nav-link @ViewBag.EmployeeAttendence " href="@Url.Action("Index", "Suppliers")"><button class="btn btn-primary" style="width: 120px; height: 45px; background-color: #152F4F;"> Suppliers </button></a>
                    <a class="nav-item nav-link @ViewBag.EmployeeAttendence " href="@Url.Action("Index", "Products")"><button class="btn btn-primary" style="width: 120px; height: 45px; background-color: #152F4F;"> Products </button></a>
                    <a class="nav-item nav-link @ViewBag.EmployeeAttendence " href="@Url.Action("Index", "Master")"><button class="btn btn-primary" style="width: 120px; height: 45px; background-color: #152F4F;"> Master Form </button></a>
                    <a class="nav-item nav-link " href="@Url.Action("LogOff", "Account")"> <button class="btn btn-primary" style="width: 120px; height: 45px; background-color: #152F4F;"><i class="fas fa-sign-out-alt"></i> Logout </button></a>
                </div>
            }

        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()

    </div>



    <footer class="footer font-small unique-color-dark" style="background-color: #152F4F; color: white;">
        <!-- Footer Links -->
        <!--<div class="container text-center text-md-left mt-0">-->

            <!-- Grid row -->
            <!--<div class="row mt-0">

                <div class="col-md-6 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">-->

                    <!-- Links -->
                    <!--<h6 class="text-uppercase font-weight-bold">Contact</h6>
                    <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
                    <p>
                        <i class="fas fa-home mr-3"></i> 12 Sonargaon Road, Sonartori Tower, 4th Floor, Dhaka-1000
                    </p>
                    <p>
                        <i class="fas fa-envelope mr-3"></i> marketing@rangs.com.bd
                    </p>

                </div>-->
                <!-- Grid column -->

            <!--</div>-->
            <!-- Grid row -->

        <!--</div>-->
        <!-- Footer Links -->
        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">
            ©Copyright: Rangs Electronics Ltd. 2021 - 2022

        </div>
        <!-- Copyright -->

    </footer>
    <!-- Footer -->


</body>
</html>
<script src="~/Scripts/fontawesome/all.min.js"></script>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
<script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
<script src="~/Scripts/popper.min.js"></script>
<script src="~/Scripts/chosen.jquery.js"></script>
<script src="~/Scripts/bootstrap-datepicker.min.js"></script>
@RenderSection("scripts", required: false)